# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomeSpotifyForm(object):
    def setupUi(self, HomeSpotifyForm):
        HomeSpotifyForm.setObjectName("HomeSpotifyForm")
        HomeSpotifyForm.resize(1500, 1000)
        HomeSpotifyForm.setMinimumSize(QtCore.QSize(0, 0))
        HomeSpotifyForm.setStyleSheet("#FormWelcome {\n"
"    background:url(D:/BiBongBenh/Desktop/CNPM/img/spotify-home.png);\n"
"}")
        self.FormWelcome = QtWidgets.QWidget(parent=HomeSpotifyForm)
        self.FormWelcome.setStyleSheet("#FormWelcome {\n"
"    back-ground:url(D:/BiBongBenh/Desktop/CNPM/img/login.png);\n"
"}")
        self.FormWelcome.setObjectName("FormWelcome")
        HomeSpotifyForm.setCentralWidget(self.FormWelcome)

        self.retranslateUi(HomeSpotifyForm)
        QtCore.QMetaObject.connectSlotsByName(HomeSpotifyForm)

    def retranslateUi(self, HomeSpotifyForm):
        _translate = QtCore.QCoreApplication.translate
        HomeSpotifyForm.setWindowTitle(_translate("HomeSpotifyForm", "MainWindow"))
