# Form implementation generated from reading ui file 'ui/welcome.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("#FormWelcome {\n"
"    background:url(D:/BiBongBenh/Desktop/CNPM/img/login_bg.png);\n"
"}")
        self.FormWelcome = QtWidgets.QWidget(parent=MainWindow)
        self.FormWelcome.setStyleSheet("#FormWelcome {\n"
"    back-ground:url(D:/BiBongBenh/Desktop/CNPM/img/login.png);\n"
"}")
        self.FormWelcome.setObjectName("FormWelcome")
        self.btnLogin = QtWidgets.QPushButton(parent=self.FormWelcome)
        self.btnLogin.setGeometry(QtCore.QRect(690, 537, 171, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setToolTip("")
        self.btnLogin.setStatusTip("")
        self.btnLogin.setAutoFillBackground(False)
        self.btnLogin.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btnLogin.setObjectName("btnLogin")
        self.btnSignUp = QtWidgets.QPushButton(parent=self.FormWelcome)
        self.btnSignUp.setGeometry(QtCore.QRect(760, 650, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btnSignUp.setFont(font)
        self.btnSignUp.setToolTip("")
        self.btnSignUp.setStatusTip("")
        self.btnSignUp.setAutoFillBackground(False)
        self.btnSignUp.setStyleSheet("")
        self.btnSignUp.setText("")
        self.btnSignUp.setObjectName("btnSignUp")
        MainWindow.setCentralWidget(self.FormWelcome)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLogin.setText(_translate("MainWindow", "LOGIN"))
