# Generated by Django 5.1 on 2024-08-16 16:55

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_musicdataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user/default_avatar.jpg', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=myapp.models.generate_user_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
