# Generated by Django 5.1 on 2024-08-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_avatar_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='store',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='science',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Science',
        ),
        migrations.DeleteModel(
            name='categoryQuiz',
        ),
        migrations.DeleteModel(
            name='quizQuestion',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
