# Generated by Django 5.1 on 2024-08-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userhistory_userlikedsongs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
        migrations.DeleteModel(
            name='UserLikedSongs',
        ),
    ]
