# Generated by Django 5.1 on 2024-08-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userhistory_userlikedsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_id', models.CharField(max_length=255, unique=True)),
                ('playlist_description', models.TextField()),
                ('playlist_image_url', models.CharField(max_length=255)),
                ('playlist_tracks_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser')),
            ],
        ),
    ]
