# Generated by Django 5.1 on 2024-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_user_playlist_playlist_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_playlist',
            name='playlist_image',
            field=models.ImageField(default='user/default_avatar.jpg', upload_to='user/'),
        ),
    ]
