# Generated by Django 5.1 on 2024-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_userhistory_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikedsongs',
            name='track_id',
            field=models.CharField(max_length=255),
        ),
    ]
