# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(1500, 1000)
        LoginForm.setMinimumSize(QtCore.QSize(0, 0))
        LoginForm.setStyleSheet("#FormWelcome {\n"
"    background:url(D:/BiBongBenh/Desktop/CNPM/img/spotify-logo.png);\n"
"}")
        self.FormWelcome = QtWidgets.QWidget(parent=LoginForm)
        self.FormWelcome.setStyleSheet("#FormWelcome {\n"
"    back-ground:url(D:/BiBongBenh/Desktop/CNPM/img/login.png);\n"
"}")
        self.FormWelcome.setObjectName("FormWelcome")
        self.label = QtWidgets.QLabel(parent=self.FormWelcome)
        self.label.setGeometry(QtCore.QRect(330, 370, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.FormWelcome)
        self.label_2.setGeometry(QtCore.QRect(320, 530, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtUserName = QtWidgets.QLineEdit(parent=self.FormWelcome)
        self.txtUserName.setGeometry(QtCore.QRect(590, 390, 381, 41))
        self.txtUserName.setObjectName("txtUserName")
        self.txtPassWord = QtWidgets.QLineEdit(parent=self.FormWelcome)
        self.txtPassWord.setGeometry(QtCore.QRect(590, 550, 381, 41))
        self.txtPassWord.setText("")
        self.txtPassWord.setObjectName("txtPassWord")
        self.btnLogin = QtWidgets.QPushButton(parent=self.FormWelcome)
        self.btnLogin.setGeometry(QtCore.QRect(630, 700, 93, 28))
        self.btnLogin.setObjectName("btnLogin")
        LoginForm.setCentralWidget(self.FormWelcome)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "MainWindow"))
        self.label.setText(_translate("LoginForm", "UserName"))
        self.label_2.setText(_translate("LoginForm", "PassWord"))
        self.txtUserName.setPlaceholderText(_translate("LoginForm", "UserName"))
        self.txtPassWord.setPlaceholderText(_translate("LoginForm", "PassWord"))
        self.btnLogin.setText(_translate("LoginForm", "Login"))
