# Form implementation generated from reading ui file 'ui/signup.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignUpForm(object):
    def setupUi(self, SignUpForm):
        SignUpForm.setObjectName("SignUpForm")
        SignUpForm.resize(1500, 1000)
        SignUpForm.setMinimumSize(QtCore.QSize(0, 0))
        SignUpForm.setStyleSheet("#FormWelcome {\n"
"    background:url(D:/BiBongBenh/Desktop/CNPM/img/spotify-logo.png);\n"
"}")
        self.FormWelcome = QtWidgets.QWidget(parent=SignUpForm)
        self.FormWelcome.setStyleSheet("#FormWelcome {\n"
"    back-ground:url(D:/BiBongBenh/Desktop/CNPM/img/login.png);\n"
"}")
        self.FormWelcome.setObjectName("FormWelcome")
        self.label = QtWidgets.QLabel(parent=self.FormWelcome)
        self.label.setGeometry(QtCore.QRect(330, 370, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.FormWelcome)
        self.label_2.setGeometry(QtCore.QRect(320, 490, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtUserName = QtWidgets.QLineEdit(parent=self.FormWelcome)
        self.txtUserName.setGeometry(QtCore.QRect(590, 390, 381, 41))
        self.txtUserName.setObjectName("txtUserName")
        self.txtPassWord = QtWidgets.QLineEdit(parent=self.FormWelcome)
        self.txtPassWord.setGeometry(QtCore.QRect(590, 510, 381, 41))
        self.txtPassWord.setText("")
        self.txtPassWord.setObjectName("txtPassWord")
        self.btnRegister = QtWidgets.QPushButton(parent=self.FormWelcome)
        self.btnRegister.setGeometry(QtCore.QRect(630, 700, 93, 28))
        self.btnRegister.setObjectName("btnRegister")
        self.label_3 = QtWidgets.QLabel(parent=self.FormWelcome)
        self.label_3.setGeometry(QtCore.QRect(320, 600, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtGmail = QtWidgets.QLineEdit(parent=self.FormWelcome)
        self.txtGmail.setGeometry(QtCore.QRect(590, 620, 381, 41))
        self.txtGmail.setText("")
        self.txtGmail.setObjectName("txtGmail")
        SignUpForm.setCentralWidget(self.FormWelcome)

        self.retranslateUi(SignUpForm)
        QtCore.QMetaObject.connectSlotsByName(SignUpForm)

    def retranslateUi(self, SignUpForm):
        _translate = QtCore.QCoreApplication.translate
        SignUpForm.setWindowTitle(_translate("SignUpForm", "MainWindow"))
        self.label.setText(_translate("SignUpForm", "UserName"))
        self.label_2.setText(_translate("SignUpForm", "PassWord"))
        self.txtUserName.setPlaceholderText(_translate("SignUpForm", "UserName"))
        self.txtPassWord.setPlaceholderText(_translate("SignUpForm", "PassWord"))
        self.btnRegister.setText(_translate("SignUpForm", "Register"))
        self.label_3.setText(_translate("SignUpForm", "Gmail"))
        self.txtGmail.setPlaceholderText(_translate("SignUpForm", "Gmail"))
